### ISSUE TITLE
Recipe with many datasets may crash when run in parallel

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1298] opened 2021-09-01 08:56 UTC
When running [recipe_impact.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_impact.yml) which uses 4 variables with 385 datasets, collecting provenance takes half an hour, while running the computations takes 1 hour in parallel and almost 2 hours with `max_parallel_tasks = 1` on my laptop (2 physical cores, 4 virtual). **This has been fixed in #1327, but the next problem persists.**

The parallel run crashes with a broken pipe error after successfully completing the last task.

Log files
------------
Run tasks sequentially (successful):
[main_log_debug_head.txt](https://github.com/ESMValGroup/ESMValCore/files/7089592/main_log_debug_head.txt)
[main_log_debug_tail.txt](https://github.com/ESMValGroup/ESMValCore/files/7089593/main_log_debug_tail.txt)

Run tasks in parallel (failed):
[main_log_debug_head.txt](https://github.com/ESMValGroup/ESMValCore/files/7089588/main_log_debug_head.txt)
[main_log_debug_tail.txt](https://github.com/ESMValGroup/ESMValCore/files/7089589/main_log_debug_tail.txt)

I uploaded only the top 1000 lines and bottom 1000 lines, because the total size is 130 MB and GitHub doesn't allow uploading files of that size.

**Comment by valeriupredoi** [comment] 2021-09-06 16:09
could the broken pipe error suggest that the buffer gets filled with too much guff from the provenance and the kill signal gets triggered while guff is still sent through the pipe, even if the initial send was accepted? Check out the second answer [here](https://stackoverflow.com/questions/4584904/what-causes-the-broken-pipe-error) - in any case, the time it takes to collect the provenance shouldn't be comparable to the time it takes to do the computations (but I can see why that's happening!)

**Comment by zklaus** [comment] 2021-10-15 14:15
I have tried rather hard to reproduce the problem, but for me it just works. @bouweandela, could you please check if the problem persists?

**Comment by bouweandela** [comment] 2022-02-03 14:13
> I have tried rather hard to reproduce the problem, but for me it just works. @bouweandela, could you please check if the problem persists?

Last time I tried it still crashed. I'm running on my laptop with 16 GB of RAM, so maybe it's just lack of memory.

**Comment by valeriupredoi** [comment] 2022-02-03 14:15
You call 16G lack of memory? Remember my Ubuntu 14 laptop from last year? I had 2G there :rofl:

**Comment by schlunma** [comment] 2022-02-04 11:23
Moving this to v2.6 since there is not open PR yet.

**Closed** 2024-04-03 19:21 UTC
Labels: bug
