### ISSUE TITLE
EC-Earth3 historical precipitation failing to save due to dodgy in ESGF replicated data (time chunk, pr, day, EC-Earth3, historical, r3i1p1f1, gr)

### ISSUE THREAD

**Issue by Karen-A-Garcia** [ESMValGroup/ESMValCore#2598] opened 2024-11-29 22:14 UTC
I was trying to preprocess some EC-Earth3 historical pr data when this issue occurred. Everything was working fine and a preprocessed file was being created and then all of a sudden, the job fails. When I checked in the main_log_debug.txt file, the issue that is raised is the following

```
2024-11-29 21:43:14,033 UTC [1952179] ERROR   esmvalcore.preprocessor:348 Failed to run preprocessor function 'save' on the data
[<iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 60265; latitude: 16; longitude: 14)>]
``` 
I'm not really sure what to do in this case since it's not a metadata issue and there wasn't much information in the debug file other than those two lines as to why it failed.

Any help or guidance would be appreciated. 🍻

Here is a larger portion of the debug file right before it failed:
```
filename = PosixPath('/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/esmvaltool_output/testing_precip_20241129_214209/preproc/all_data/precipitation/CMIP6_EC-Earth3_day_historical_r3i1p1f1_pr_gr_1850-2014.nc')
2024-11-29 21:43:03,512 UTC [1952179] DEBUG   esmvalcore.preprocessor._io:452 Saving cube:
precipitation_flux / (kg m-2 s-1)   (time: 60265; latitude: 16; longitude: 14)
    Dimension coordinates:
        time                             x                -              -
        latitude                         -                x              -
        longitude                        -                -              x
    Cell methods:
        0                           area: time: mean
    Attributes:
        Conventions                 'CF-1.7 CMIP-6.2'
        activity_id                 'CMIP'
        branch_method               'standard'
        branch_time                 0.0
        branch_time_in_child        0.0
        branch_time_in_parent       0.0
        cmor_version                '3.4.0'
        contact                     'cmip6-data@ec-earth.org'
        data_specs_version          '01.00.29'
        experiment                  'all-forcing simulation of the recent past'
        experiment_id               'historical'
        external_variables          'areacella'
        forcing_index               1
        frequency                   'day'
        further_info_url            'https://furtherinfo.es-doc.org/CMIP6.EC-Earth-Consortium.EC-Earth3.his ...'
        grid                        'T255L91'
        grid_label                  'gr'
        initialization_index        1
        institution                 'AEMET, Spain; BSC, Spain; CNR-ISAC, Italy; DMI, Denmark; ENEA, Italy; FMI, ...'
        institution_id              'EC-Earth-Consortium'
        license                     'CMIP6 model data produced by EC-Earth-Consortium is licensed under a Creative ...'
        mip_era                     'CMIP6'
        nominal_resolution          '100 km'
        parent_activity_id          'CMIP'
        parent_experiment_id        'piControl'
        parent_mip_era              'CMIP6'
        parent_source_id            'EC-Earth3'
        parent_time_units           'days since 1850-1-1 00:00:00'
        parent_variant_label        'r1i1p1f1'
        physics_index               1
        product                     'model-output'
        realization_index           3
        realm                       'atmos'
        source                      'EC-Earth3 (2019): \naerosol: none\natmos: IFS cy36r4 (TL255, linearly reduced ...'
        source_id                   'EC-Earth3'
        source_type                 'AOGCM'
        sub_experiment              'none'
        sub_experiment_id           'none'
        table_id                    'day'
        table_info                  'Creation Date:(08 March 2019) MD5:a50b2af30eeecaae49684260f5d43db4'
        title                       'EC-Earth3 output prepared for CMIP6'
        variable_id                 'pr'
        variant_label               'r3i1p1f1'
with lazy data to /space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/esmvaltool_output/testing_precip_20241129_214209/preproc/all_data/precipitation/CMIP6_EC-Earth3_day_historical_r3i1p1f1_pr_gr_1850-2014.nc
2024-11-29 21:43:14,033 UTC [1952179] ERROR   esmvalcore.preprocessor:348 Failed to run preprocessor function 'save' on the data
[<iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 60265; latitude: 16; longitude: 14)>]
```

**Comment by bouweandela** [comment] 2024-11-30 19:52
When saving lazy data, the data is read from the input file and computed. Therefore, something likely went wrong when computing the data (e.g. you ran out of memory) or saving the data (e.g. you ran out of disk space). Maybe there was information written to the terminal (stdout/stderr) that can help you debug this issue? Is it reproducible?

**Comment by valeriupredoi** [comment] 2024-12-02 22:56
Ouch, that's a thread unsafety issue. You are also using a rather old iris ie 3.7. Try upgrading itis to the latest 3.11, and see if you can reproduce the issue please. If you can, then the netCDF4 global lock may be at fault, and we'll have to talk to the iris folks. Good catch btw! @bouweandela you didn't trust me when I was on about thread unsafe events and iris eh 😁😁

**Comment by Karen-A-Garcia** [comment] 2024-12-02 23:37
Thanks for pointing that out! I've updated iris and unfortunately, I still get the error. :(

Here's a copy of the Traceback:
```
Traceback (most recent call last):
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_main.py", line 518, in run
    fire.Fire(ESMValTool())
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_main.py", line 405, in run
    self._run(recipe, session)
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_main.py", line 447, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_main.py", line 130, in process_recipe
    recipe.run()
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_recipe/recipe.py", line 1075, in run
    self.tasks.run(max_parallel_tasks=self.session['max_parallel_tasks'])
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_task.py", line 738, in run
    self._run_parallel(address, max_parallel_tasks)
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_task.py", line 782, in _run_parallel
    _copy_results(task, running[task])
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_task.py", line 805, in _copy_results
    task.output_files, task.products = future.get()
                                       ^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_task.py", line 816, in _run_task
    output_files = task.run()
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/_task.py", line 264, in run
    self.output_files = self._run(input_files)
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/preprocessor/__init__.py", line 664, in _run
    product.close()
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/preprocessor/__init__.py", line 497, in close
    self.save()
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/preprocessor/__init__.py", line 488, in save
    preprocess(self._cubes,
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/preprocessor/__init__.py", line 374, in preprocess
    result.append(_run_preproc_function(function, items, settings,
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/preprocessor/__init__.py", line 323, in _run_preproc_function
    return function(items, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/esmvalcore/preprocessor/_io.py", line 479, in save
    iris.save(cubes, **kwargs)
      ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/iris/io/__init__.py", line 503, in save
    result = saver(source, target, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/iris/fileformats/netcdf/saver.py", line 2747, in save
    with Saver(filename, netcdf_format, compute=compute) as sman:
      ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/iris/fileformats/netcdf/saver.py", line 437, in __exit__
    self.complete()
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/iris/fileformats/netcdf/saver.py", line 2384, in complete
    self.delayed_completion().compute()
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/dask/base.py", line 342, in compute
    (result,) = compute(self, traverse=False, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkg001/miniconda3/envs/esmvaltool/lib/python3.11/site-packages/iris/fileformats/netcdf/_thread_safe_nc.py", line 339, in __getitem__
    var = variable[keys]
    ^^^^^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 4958, in netCDF4._netCDF4.Variable.__getitem__
  File "src/netCDF4/_netCDF4.pyx", line 5916, in netCDF4._netCDF4.Variable._get
  File "src/netCDF4/_netCDF4.pyx", line 2029, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
2024-12-02 23:33:48,413 UTC [3712571] INFO    esmvalcore._main:534 
If you have a question or need help, please start a new discussion on https://github.com/ESMValGroup/ESMValTool/discussions
If you suspect this is a bug, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues
To make it easier to find out what the problem is, please consider attaching the files run/recipe_*.yml and run/main_log_debug.txt from the output directory. 
```

**Comment by bouweandela** [comment] 2024-12-03 13:09
It looks like at least one of the input files is damaged. I was able to reproduce the issue using:
```
ncdump -v pr /home/bandela/climate_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r3i1p1f1/day/pr/gr/v20200730/pr_day_EC-Earth3_historical_r3i1p1f1_gr_18500101-18501231.nc`
```
gives:
```
NetCDF: HDF error
Location: file ?; fcn ? line 478
```

**Comment by valeriupredoi** [comment] 2024-12-03 13:49
the CEDA-JASMIN file seems to be healthy:
```
[valeriu@sci2 ~]$ ncdump -h /badc/cmip6/data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r3i1p1f1/day/pr/gr/v20200730/pr_day_EC-Earth3_historical_r3i1p1f1_gr_18500101-18501231.nc
netcdf pr_day_EC-Earth3_historical_r3i1p1f1_gr_18500101-18501231 {
dimensions:
	time = UNLIMITED ; // (365 currently)
	lat = 256 ;
	lon = 512 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 1850-01-01 00:00:00" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
		time:calendar = "gregorian" ;
	double time_bnds(time, bnds) ;
	double lat(lat) ;
		lat:bounds = "lat_bnds" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:long_name = "Latitude" ;
		lat:standard_name = "latitude" ;
	double lat_bnds(lat, bnds) ;
	double lon(lon) ;
		lon:bounds = "lon_bnds" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:long_name = "Longitude" ;
		lon:standard_name = "longitude" ;
	double lon_bnds(lon, bnds) ;
	float pr(time, lat, lon) ;
		pr:standard_name = "precipitation_flux" ;
		pr:long_name = "Precipitation" ;
		pr:comment = "includes both liquid and solid phases" ;
		pr:units = "kg m-2 s-1" ;
		pr:cell_methods = "area: time: mean" ;
		pr:cell_measures = "area: areacella" ;
		pr:history = "2019-07-08T09:29:38Z altered by CMOR: Reordered dimensions, original order: lat lon time." ;
		pr:missing_value = 1.e+20f ;
		pr:_FillValue = 1.e+20f ;

// global attributes:
		:Conventions = "CF-1.7 CMIP-6.2" ;
		:activity_id = "CMIP" ;
		:branch_method = "standard" ;
		:branch_time = 0. ;
		:branch_time_in_child = 0. ;
		:branch_time_in_parent = 0. ;
		:contact = "cmip6-data@ec-earth.org" ;
		:creation_date = "2019-07-08T09:29:40Z" ;
		:data_specs_version = "01.00.29" ;
		:experiment = "all-forcing simulation of the recent past" ;
		:experiment_id = "historical" ;
		:external_variables = "areacella" ;
		:forcing_index = 1 ;
		:frequency = "day" ;
		:further_info_url = "https://furtherinfo.es-doc.org/CMIP6.EC-Earth-Consortium.EC-Earth3.historical.none.r3i1p1f1" ;
		:grid = "T255L91" ;
		:grid_label = "gr" ;
		:initialization_index = 1 ;
		:institution = "AEMET, Spain; BSC, Spain; CNR-ISAC, Italy; DMI, Denmark; ENEA, Italy; FMI, Finland; Geomar, Germany; ICHEC, Ireland; ICTP, Italy; IDL, Portugal; IMAU, The Netherlands; IPMA, Portugal; KIT, Karlsruhe, Germany; KNMI, The Netherlands; Lund University, Sweden; Met Eireann, Ireland; NLeSC, The Netherlands; NTNU, Norway; Oxford University, UK; surfSARA, The Netherlands; SMHI, Sweden; Stockholm University, Sweden; Unite ASTR, Belgium; University College Dublin, Ireland; University of Bergen, Norway; University of Copenhagen, Denmark; University of Helsinki, Finland; University of Santiago de Compostela, Spain; Uppsala University, Sweden; Utrecht University, The Netherlands; Vrije Universiteit Amsterdam, the Netherlands; Wageningen University, The Netherlands. Mailing address: EC-Earth consortium, Rossby Center, Swedish Meteorological and Hydrological Institute/SMHI, SE-601 76 Norrkoping, Sweden" ;
		:institution_id = "EC-Earth-Consortium" ;
		:mip_era = "CMIP6" ;
		:nominal_resolution = "100 km" ;
		:parent_activity_id = "CMIP" ;
		:parent_experiment_id = "piControl" ;
		:parent_mip_era = "CMIP6" ;
		:parent_source_id = "EC-Earth3" ;
		:parent_time_units = "days since 1850-01-01" ;
		:parent_variant_label = "r1i1p1f1" ;
		:physics_index = 1 ;
		:product = "model-output" ;
		:realization_index = 3 ;
		:realm = "atmos" ;
		:source = "EC-Earth3 (2019): \n",
			"aerosol: none\n",
			"atmos: IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level 0.01 hPa)\n",
			"atmosChem: none\n",
			"land: HTESSEL (land surface scheme built in IFS)\n",
			"landIce: none\n",
			"ocean: NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)\n",
			"ocnBgchem: none\n",
			"seaIce: LIM3" ;
		:source_id = "EC-Earth3" ;
		:source_type = "AOGCM" ;
		:sub_experiment = "none" ;
		:sub_experiment_id = "none" ;
		:table_id = "day" ;
		:table_info = "Creation Date:(08 March 2019) MD5:a50b2af30eeecaae49684260f5d43db4" ;
		:title = "EC-Earth3 output prepared for CMIP6" ;
		:variable_id = "pr" ;
		:variant_label = "r3i1p1f1" ;
		:license = "CMIP6 model data produced by EC-Earth-Consortium is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at http://www.ec-earth.org. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." ;
		:cmor_version = "3.4.0" ;
		:_NCProperties = "version=2,netcdf=4.6.2,hdf5=1.10.4" ;
		:tracking_id = "hdl:21.14100/63baa393-abab-4010-9403-ea6bf756af36" ;
		:history = "Sat Sep  7 01:22:29 2019: ncatted -O -a calendar,time,m,c,gregorian ./CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r3i1p1f1/day/pr/gr/v20190515/pr_day_EC-Earth3_historical_r3i1p1f1_gr_18500101-18501231.nc\n",
			"2019-07-08T09:25:26Z ; CMOR rewrote data to be consistent with CMIP6, CF-1.7 CMIP-6.2 and CF standards.;\n",
			"processed by ece2cmor v1.0.0, git rev. 9199cacf092acf324cd6bfe3efcba4ac31b04fb4-changes\n",
			"The cmor-fixer version v1.0 script has been applied.The cmor-fixer version v1.0 script has been applied." ;
```

I even ran some basic analysis on it, which failed miserable :rofl: - but that's very helpful since this isolates the issue with the file:

```python
import iris
print(iris.__version__)

fi = "/badc/cmip6/data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r3i1p1f1/day/pr/gr/v20200730/pr_day_EC-Earth3_historical_r3i1p1f1_gr_18500101-18501231.nc"
c = iris.load_cube(fi)
print(c.data[22])
```

outputs
```
[valeriu@sci2 ~]$ python testec.py
3.7.0
ERROR 1: PROJ: proj_create_from_database: Open of /apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/share/proj failed
/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/iris/fileformats/cf.py:859: UserWarning: Missing CF-netCDF measure variable 'areacella', referenced by netCDF variable 'pr'
  warnings.warn(
HDF5-DIAG: Error detected in HDF5 (1.14.0) thread 1:
  #000: H5D.c line 1069 in H5Dread(): can't synchronously read data
    major: Dataset
    minor: Read failed
  #001: H5D.c line 1013 in H5D__read_api_common(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5VLcallback.c line 2092 in H5VL_dataset_read_direct(): dataset read failed
    major: Virtual Object Layer
    minor: Read failed
  #003: H5VLcallback.c line 2048 in H5VL__dataset_read(): dataset read failed
    major: Virtual Object Layer
    minor: Read failed
  #004: H5VLnative_dataset.c line 361 in H5VL__native_dataset_read(): can't read data
    major: Dataset
    minor: Read failed
  #005: H5Dio.c line 370 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #006: H5Dchunk.c line 2863 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #007: H5Dchunk.c line 4499 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #008: H5Z.c line 1384 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #009: H5Zdeflate.c line 117 in H5Z__filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
Traceback (most recent call last):
  File "/home/users/valeriu/testec.py", line 6, in <module>
    print(c.data[22])
          ^^^^^^
  File "/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/iris/cube.py", line 2466, in data
    return self._data_manager.data
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/iris/_data_manager.py", line 206, in data
    result = as_concrete_data(self._lazy_array)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/iris/_lazy_data.py", line 288, in as_concrete_data
    (data,) = _co_realise_lazy_arrays([data])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/iris/_lazy_data.py", line 251, in _co_realise_lazy_arrays
    computed_arrays = da.compute(*arrays)
                      ^^^^^^^^^^^^^^^^^^^
  File "/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/dask/base.py", line 665, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/jasmin/community/esmvaltool/miniconda3_py311_23.11.0-2/envs/esmvaltool/lib/python3.11/site-packages/iris/fileformats/netcdf/_thread_safe_nc.py", line 344, in __getitem__
    var = variable[keys]
          ~~~~~~~~^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 4958, in netCDF4._netCDF4.Variable.__getitem__
  File "src/netCDF4/_netCDF4.pyx", line 5916, in netCDF4._netCDF4.Variable._get
  File "src/netCDF4/_netCDF4.pyx", line 2029, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

Now, loading it in netcdf4-python:

```python
mport netCDF4

ds = netCDF4.Dataset(fi)
print(ds)
```

gives us even more info:
```
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    Conventions: CF-1.7 CMIP-6.2
...
```

so the metadata is accessible, the file is NETCDF4_CLASSIC, the variable is accessible:
```
<class 'netCDF4._netCDF4.Variable'>
float32 pr(time, lat, lon)
    standard_name: precipitation_flux
    long_name: Precipitation
    comment: includes both liquid and solid phases
    units: kg m-2 s-1
    cell_methods: area: time: mean
    cell_measures: area: areacella
    history: 2019-07-08T09:29:38Z altered by CMOR: Reordered dimensions, original order: lat lon time.
    missing_value: 1e+20
    _FillValue: 1e+20
unlimited dimensions: time
current shape = (365, 256, 512)
```

but accessing its data can oly be done point-wise eg `ds['pr'][100]`, an immediate access of the entire data fails:
```
ds['pr'][:]

Traceback (most recent call last):
  File "/home/users/valeriu/testec.py", line 11, in <module>
    print(ds['pr'][:])
          ~~~~~~~~^^^
  File "src/netCDF4/_netCDF4.pyx", line 4958, in netCDF4._netCDF4.Variable.__getitem__
  File "src/netCDF4/_netCDF4.pyx", line 5916, in netCDF4._netCDF4.Variable._get
  File "src/netCDF4/_netCDF4.pyx", line 2029, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

and after faffing with it for a wee more, I found out there an issue with the chunking along the time-axis (the normal chunking axis), since it's got a hard time getting items and returning values for eg time slices `print(ds['pr'][100:364, :, :])` but print(ds['pr'][200:364, :, :])` works so this means there's an issue with a chunk between 100 and 200. That's as far as I can go :grin:

**Comment by valeriupredoi** [comment] 2024-12-03 14:00
chunking is [1, 256, 512] so it's a contiguous time chunk, file is compressed with zlib, filters are {'zlib': True, 'szip': False, 'zstd': False, 'bzip2': False, 'blosc': False, 'shuffle': False, 'complevel': 1, 'fletcher32': False}, so am fairly sure that was an issue when data was spat to disk, initially, at file creation (not replication) point. Not much we can do, am quite sure they don't want to re-CMORize their model data since it's CMIP6

**Comment by valeriupredoi** [comment] 2024-12-04 13:16
looks like they had similar issues with other variables too https://errata.ipsl.fr/static/view.html?uid=d76a6300-176e-9047-8146-c666f2c4af76 - this is what's affecting this case (very low values), probably why the C-layer has issues getting items

**Comment by valeriupredoi** [comment] 2024-12-04 13:21
and, as expected, even for critical issues like https://errata.ipsl.fr/static/view.html?uid=e2f66940-d13f-74c3-aa3b-a4547918ba1f they won't fix since cmip6 is too old

**Comment by bouweandela** [comment] 2024-12-04 15:53
Closing this since we cannot do much about it.

**Closed by bouweandela** 2024-12-04 15:53 UTC
Labels: data issue

**Comment by valeriupredoi** [comment] 2024-12-04 16:55
agreed, sadly - let's keep them in check for CMIP7 :grin:
