### ISSUE TITLE
Preprocessor memory usage is excessive and error messages unclear.

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#51] opened 2019-01-29 10:21 UTC
This issue was raised in pr #763 and was also raised by Rob Parker, from the UKESM project.

The recipe `recipe_ocean_bgc.yml` memory explodes when the time range is changed to a more realistic range. The time range is currently 2001-2004, but we may be interested in, for instance, the range 1950-2010.

The second problem is that the warning messages and error messages related to Memory problems in ESMValTool are unclear. It's not obvious which part of this recipe causes the memory problems.

**Comment by mattiarighi** [comment] 2019-06-11 09:36
This looks like a duplicate of #32, can we close?

**Comment by bouweandela** [comment] 2019-06-12 13:26
I think not, there are more ways to reduce memory usage than using iris and dask. Some things will have to be implemented in iris too, e.g. lazy regridding/vertical level interpolation. For multimodel statististics we could consider saving data to disk more to reduce memory use, though that will be another performance problem.

**Comment by npgillett** [comment] 2020-09-18 17:55
It looks like someone has optimised the memory usage of the preprocessor in the last few months - my code with ~1500 input files used to run out of memory and crash when I ran in one go in the spring, now it works! Thanks! That said, according to the resource_usage.txt file, the memory used still seems to progressively increase through the run and never decrease, which I don't fully understand, since I would have thought that after each is file is preprocessed and written out, that the memory used would be freed up.
[resource_usage.txt](https://github.com/ESMValGroup/ESMValCore/files/5247326/resource_usage.txt)
[recipe_gillett20.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/5247332/recipe_gillett20.yml.txt)
(Or perhaps resource_usage.txt shows some kind of cumulative total, rather than actual instantaneous memory usage?)

In any case, I'm not going to complain too much, since my code now runs, but just thought I'd ask... Thanks!

**Comment by schlunma** [comment] 2023-08-29 07:54
It looks like most of the issues discussed here (lazy regridding, lazy vertical level interpolation, lazy multimodel statistics, an overview of memory usage, etc.) has been fixed in previous releases. Remaining problems can be discussed in  https://github.com/ESMValGroup/ESMValCore/issues/674 or in dedicated issues.

**Closed by schlunma** 2023-08-29 07:54 UTC
Labels: preprocessor
