### ISSUE TITLE
Apply precommit hooks to all files before next release

### ISSUE THREAD

**Issue by jvegreg** [ESMValGroup/ESMValCore#926] opened 2021-01-05 12:28 UTC
Since we added the pre-commit hooks we started to see cluttered changelogs in the pull requests due to them fixing whole files instead of the parts that were modified by the author. It will be nice to reformat all files just before starting the release tests of v2.2.0 to avoid this in the future.

**Comment by valeriupredoi** [comment] 2021-01-05 12:49
I am a fan of this :grin:

**Comment by bouweandela** [comment] 2021-01-05 12:50
I think we need to drastically reduce the number of open pull requests before we automatically reformat the entire code base, because doing so will introduce merge conflicts everywhere.

Until that is done, we need to use pre-commit sparingly and with care. I would also like to try and change pre-commit so it reformats only the code that is changed using the `yapf-diff` command that will be available with the next release of yapf.

**Comment by jvegasbsc** [comment] 2021-01-05 13:03
> I think we need to drastically reduce the number of open pull requests before we automatically reformat the entire code base, because doing so will introduce merge conflicts everywhere.

Yes, I know. This is the main reason I plan to do it at the code freeze, as most of the `almost ready` work should be merged already. 

Anyway, I am not so sure about the merge conflicts. The output of those is reproducible, so it will look the same if you started before or after the reformat if you run them. We will see a lot of them from people that does not have them configured, though.

 I was not aware of the `yapf-diff` command coming soon when I wrote this.

**Comment by stefsmeets** [comment] 2021-02-01 13:42
This might be a good opportunity to pin the versions of our formatting tools (`yapf`, `isort`, and the likes). `pre-commit` started to raise warnings like these recently:

```
[WARNING] The 'rev' field of repo 'https://github.com/adrienverge/yamllint' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.
```

To update the versions in `pre-commit-config.yaml`: `pre-commit autoupdate`. May be useful to synchronize the versions with `setup.py`.

**Comment by jvegasbsc** [comment] 2021-02-03 10:04
Regarding this, I spotted that `pre-commit` has its own action that we can enforce in PR: https://github.com/pre-commit/action

I think it will make our life easier

**Comment by bouweandela** [comment] 2021-02-03 10:27
Note that some tools that pre-commit runs do return lots of false positive, e.g. the spellchecker will always recommend to correct the wind speed variable `vas` to the word `was`, so I'm not sure how useful it is to run this action. We already have `flake8` integrated in pytest.

**Comment by stefsmeets** [comment] 2021-02-03 11:00
> 
> 
> Note that some tools that pre-commit runs do return lots of false positive, e.g. the spellchecker will always recommend to correct the wind speed variable `vas` to the word `was`, so I'm not sure how useful it is to run this action. We already have `flake8` integrated in pytest.

We can configure codespell to ignore these in `setup.cfg`: https://github.com/codespell-project/codespell#using-a-config-file

**Comment by bouweandela** [comment] 2024-10-03 09:54
Done in #2524

**Closed by bouweandela** 2024-10-03 09:54 UTC
Labels: enhancement
