### ISSUE TITLE
supplementary variables disappear from cubes after extract_region

### ISSUE THREAD

**Issue by rebeccaherman1** [ESMValGroup/ESMValCore#2162] opened 2023-08-02 10:34 UTC
After poking around a bit more, I believe that the `cell_measures` and all other supplementary variables actually are disappearing from the cubes upon applying `extract_region`, whereas I would have expected information from spatially-anchored supplementary variables simply to be extracted over the same region. This seems like a major shortcoming to me, not least because to use `area_statistics` (which requires `cell_area`) over any specific region, you need to use `extract_region` first. 

### Discussed in https://github.com/ESMValGroup/ESMValCore/discussions/2161

<div type='discussions-op-text'>

<sup>Originally posted by **rebeccaherman1** August  1, 2023</sup>
I am using [this notebook](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/notebooks/loading-and-processing-data.html) as a guide while I attempt to develop my recipe and diagnostic scripts. Upon loading the initial cube, I believe I see that the supplementary variable `areacella` included in the cube as `cell_area` under `Cell measures`, but the moment I restrict the domain with `extract_region`, `Cell measures` disappears, taking `cell_area` with it. Is areacella no longer part of the cube? If it is, where did it go?</div>

**Comment by valeriupredoi** [comment] 2023-08-02 12:52
hi @rebeccaherman1 could be able to provide me with a minimal recipe that I can use to replicate this behaviour please? :beer:

**Comment by rebeccaherman1** [comment] 2023-08-02 15:29
@valeriupredoi Here's a notebook:
[extract_region_supplementary_example.zip](https://github.com/ESMValGroup/ESMValCore/files/12241810/extract_region_supplementary_example.zip)

Would you prefer to have it in a different format? I could potentially dump my cube into a pkl file and shorten the notebook.

Thank you!

**Comment by valeriupredoi** [comment] 2023-08-02 16:00
cheers @rebeccaherman1 - could you pls give me the recipe you are running, or, if you are not running a recipe, a minimal reproducible Python code that I can run, sorry, Notebooks are too fancy for my 1990s ways of reproducing issues :laughing:

**Comment by rebeccaherman1** [comment] 2023-08-03 07:37
@valeriupredoi no worries :)
I've been finding it easier to debug in the notebook; I'll turn it into a recipe when it works the way I want it to.
In the meantime, here's a python script version of it:
[extract_region_supplementary.zip](https://github.com/ESMValGroup/ESMValCore/files/12248121/extract_region_supplementary.zip)
(sorry I didn't see your response right away)

**Comment by rebeccaherman1** [comment] 2023-08-03 08:10
A rather confusing (at least to me) update:
This behavior seems to be dependent on the region that I extract!

`cell_area` and `land_area_fraction` disappear when I use the region `[-90,40]x[20,80]`, but remain when I use the region `[160,280]x[-5,5]`. I have no idea what to make of this.

**Comment by valeriupredoi** [comment] 2023-08-03 11:17
no worries @rebeccaherman1 - I think I can make do with your Python script yu attached above - I'll have a looksee at what/how it does things and I'll investigate the fairly bizarre cases you are seeing :+1:

**Comment by valeriupredoi** [comment] 2023-08-03 14:27
@rebeccaherman1 I have tried to reproduce this issue, and I used a pytest-like Python test script:
```python
import os
import iris
import esmvalcore.preprocessor as pp

from esmvalcore.dataset import Dataset
from esmvalcore.config import CFG
from esmvalcore.esgf import download, ESGFFile


root_fil = "/home/valeriu/climate_data/CMIP6/CMIP/NCAR/CESM2/piControl/r1i1p1f1/Amon/psl/gn/v20190320"
CESM2 = Dataset(
    mip='Amon',
    project='CMIP6',
    dataset='CESM2',
    ensemble='*',
    exp='piControl',
    timerange='P501Y/*',
    grid='gn'
)
CFG['search_esgf'] = 'when_missing'

def add_facet(D, fname, fvalue):
    R = D.copy()
    R.facets[fname]=fvalue
    R.augment_facets()
    return R


def get_files(D):
    D.find_files()
    files = list(D.files)
    for supplementary_ds in D.supplementaries:
        files.extend(supplementary_ds.files)
    files = [file for file in files if isinstance(file, ESGFFile)]
    if(len(files)>0):
        print("Downloading Files:")
        print(files)
        download(files, CFG['download_dir'])
    D.find_files()
    return D


def bug_extract_region():
    """Test bug of reg extract."""
    NAO_xlim = [-90, 40]
    NAO_ylim = [20, 80]
    files = os.listdir(root_fil)

    # individual files
    for fil in files:
        print(fil)
        psl = iris.load_cube(os.path.join(root_fil, fil))
        print(f"Initial cell measures: {psl.cell_methods}")
        test = pp.extract_region(psl,
                                 start_longitude=NAO_xlim[0],
                                 end_longitude=NAO_xlim[1],
                                 start_latitude=NAO_ylim[0],
                                 end_latitude=NAO_ylim[1])
        print(f"Final cell measures: {test.cell_methods}")

    # cubelist concatenated into one cube
    cube_list = iris.cube.CubeList(
        [iris.load_cube(os.path.join(root_fil, fil)) for fil in files]
    )
    cubes = pp.concatenate(cube_list)
    test = pp.extract_region(cubes,
                             start_longitude=NAO_xlim[0],
                             end_longitude=NAO_xlim[1],
                             start_latitude=NAO_ylim[0],
                             end_latitude=NAO_ylim[1])
    print(test)
    print(f"Final cell measure concat cubes: {test.cell_methods}")

    # use Dataset object
    psl = get_files(add_facet(CESM2, 'short_name', 'psl'))
    ps = psl.load()
    ds_test = pp.extract_region(ps,
                                start_longitude=NAO_xlim[0],
                                end_longitude=NAO_xlim[1],
                                start_latitude=NAO_ylim[0],
                                end_latitude=NAO_ylim[1])
    print(ds_test)
    print(f"DATASET Final cell measures: {ds_test.cell_methods}")


if __name__ == '__main__':
    bug_extract_region()
```

You can run it yourself by simply changing the `root_fil` to point to where your data is stored (run it like any bogstandard Python script) - I don't see any loss of `CellMethod()` in any of the cubes, after looking at each of the files individually, nor after concatenating them into a single cube - all this using the pure iris load, nor after invoking the `Dataset` class and doing everything using it (see the third test case inside the function. Moreover I looked at the two cubes (the concatenated cube loaded by pure iris and the one obtained from filtering the data through `Dataset` class) and they are (almost) identical - almost here since `Dataset` fixes time axes, attributes etc. I have run this with esmvalcore=2.9.0. Could you please maybe grab this code, run it with the esmvalcore version I ran it with, and point to me what you think it's wrong/missing? I am attaching it as a txt file as well, for ease of download from here, just rename it :beer: 
[bug_extract_region.py.txt](https://github.com/ESMValGroup/ESMValCore/files/12251823/bug_extract_region.py.txt)

**Comment by rebeccaherman1** [comment] 2023-08-03 15:07
try this? and maybe repeat with `ancillary_variables` instead of `cell_measures`?

```python
import os
import iris
import esmvalcore.preprocessor as pp

from esmvalcore.dataset import Dataset
from esmvalcore.config import CFG
from esmvalcore.esgf import download, ESGFFile


root_fil = "/home/valeriu/climate_data/CMIP6/CMIP/NCAR/CESM2/piControl/r1i1p1f1/Amon/psl/gn/v20190320"
CESM2 = Dataset(
    mip='Amon',
    project='CMIP6',
    dataset='CESM2',
    ensemble='*',
    exp='piControl',
    timerange='P501Y/*',
    grid='gn'
)
for s in ['areacella', 'sftlf']:
    CESM2.add_supplementary(short_name=s, mip='fx')     #ADDED CODE HERE

CFG['search_esgf'] = 'when_missing'

def add_facet(D, fname, fvalue):
    R = D.copy()
    R.facets[fname]=fvalue
    R.augment_facets()
    return R


def get_files(D):
    D.find_files()
    files = list(D.files)
    for supplementary_ds in D.supplementaries:
        files.extend(supplementary_ds.files)
    files = [file for file in files if isinstance(file, ESGFFile)]
    if(len(files)>0):
        print("Downloading Files:")
        print(files)
        download(files, CFG['download_dir'])
    D.find_files()
    return D


def bug_extract_region():
    """Test bug of reg extract."""
    NAO_xlim = [-90, 40]
    NAO_ylim = [20, 80]
    files = os.listdir(root_fil)

    # individual files
    for fil in files:
        print(fil)
        psl = iris.load_cube(os.path.join(root_fil, fil))
        print(f"Initial cell measures: {psl.cell_measures}")       #CHANGED 
        test = pp.extract_region(psl,
                                 start_longitude=NAO_xlim[0],
                                 end_longitude=NAO_xlim[1],
                                 start_latitude=NAO_ylim[0],
                                 end_latitude=NAO_ylim[1])
        print(f"Final cell measures: {test.cell_measures}")              #CHANGED

    # cubelist concatenated into one cube
    cube_list = iris.cube.CubeList(
        [iris.load_cube(os.path.join(root_fil, fil)) for fil in files]
    )
    cubes = pp.concatenate(cube_list)
    test = pp.extract_region(cubes,
                             start_longitude=NAO_xlim[0],
                             end_longitude=NAO_xlim[1],
                             start_latitude=NAO_ylim[0],
                             end_latitude=NAO_ylim[1])
    print(test)
    print(f"Final cell measure concat cubes: {test.cell_measures}")          #CHANGED

    # use Dataset object
    psl = get_files(add_facet(CESM2, 'short_name', 'psl'))
    ps = psl.load()
    ds_test = pp.extract_region(ps,
                                start_longitude=NAO_xlim[0],
                                end_longitude=NAO_xlim[1],
                                start_latitude=NAO_ylim[0],
                                end_latitude=NAO_ylim[1])
    print(ds_test)
    print(f"DATASET Final cell measures: {ds_test.cell_measures}")           #CHANGED


if __name__ == '__main__':
    bug_extract_region()
```

[bug_extract_region_edited.py.txt](https://github.com/ESMValGroup/ESMValCore/files/12252176/bug_extract_region_edited.py.txt)

**Comment by valeriupredoi** [comment] 2023-08-03 15:32
also, as an advice - please run your things using a recipe - that way you are guaranteed to make full use of the power of the preprocessor since the preprocessing chain is executed correctly and uses its internal functionalities in the correct manner :smiley:

**Comment by rebeccaherman1** [comment] 2023-08-04 10:14
@valeriupredoi Thank you for the explanation. I'd like to continue the discussion about this, because I am having trouble squaring your explanation with what I think I understand from the docs. 

[Section 7.3 of the conventions](https://cfconventions.org/cf-conventions/cf-conventions.html#cell-measures) seems to describe `cell_methods` as a list of methods that have *already* been applied to the data, so that one can understand what the data represents. This is consistent with what I observed in my jupyter notebook as I applied progressive methods to my cubes. Am I misunderstanding the purpose of this field?

On the other hand, `cell_measures` (described in section 7.2 of the previous link) and `ancillary_variables` seem to be [directly cited](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#preprocessors-using-supplementary-variables) as necessary for certain preprocessing functions that you may want to apply in the future. I see that some of the functions error when they are not provided the necessary `cell_measures` and `ancillary_variables`, but other functions (such as `mask_landsea`) replace it when possible with standard geological data, which is better than nothing, but not comparable to using the field from the model's native grid. 

(For reasons like this, I'm still finding it preferable at the moment to be able to interact with the contents of my script at every stage in a jupyter notebook, rather than having to submit dozens of jobs that all fail or may produce output different than I expected without a warning that I can understand. Maybe with a recipe I get more power from the software, but I am not familiar enough with it yet to know for sure what I'm actually doing, and right now I'm finding transparency and discoverability to be more important.)

If it is true that the information from `cell_measures` and `ancillary_variables` is somehow contained in `cell_methods`, could you help me understand or point me to where I can read about it? Is it possible then to retrieve the `areacella` and `sftlf` values from the `cell_methods`? Also, if this is the case, then I think the documentation about supplementary variables (especially that second link in this post) needs to be updated to make this clear.

**Comment by valeriupredoi** [comment] 2023-08-04 12:36
Hi @rebeccaherman1 many thanks for the detailed description above - I will follow it up with a more detailed comment (on the best way to use what not) but for now, I am investigating a potential bug with cube intersection, as a result of your example above - cheers muchly for persisting about it, since that made me go deeper in the analysis and start chasing this potential :bug: I'll be back :grin:

**Comment by valeriupredoi** [comment] 2023-08-04 14:09
@rebeccaherman1 very many thanks for all this casing up, I did eventually raise an issue with iris https://github.com/SciTools/iris/issues/5413

As for your specific case here, it is unclear to me just yet what the best approach would be - it is indeed a bug an iris, so that will affect both the way you are running here by directly importing and using esmvalcore functionality, and the recipe-based approach that sets up a preprocessing chain - all these are at a higher level, so they'll both be affected. Is this something urgen for you? If it is, we can try and plop a temporary bugfix - @schlunma @sloosvel what you guys think?

Incidentally, and that's for @bouweandela - I noticed that the script off the iPython notebook that Rebecca is using (see above) is extremely inefficient: it takes a fairly long time, chucks in a lot more memory than it should, and, on top of everything else (and this is new to me) it writes a bunch of actual data to disk (no idea where though - still to figure out, and no, it's not the ESGF data, that gets downloaded once - it writes a fair bit of data everytime the script is run), what in the actual is going on? :beer:

**Comment by valeriupredoi** [comment] 2023-08-04 14:52
gotcha! Found the reason why slow, memory-intesive, and eating up disk: I had `save_intermediary_cubes` set to True in my user config, as a result the loading of a `Dataset` object leads to the unwanted creation of an `esmvaltool_output` dir, with a session hash, where intermediary files are stored:
```
(esmvaltool) valeriu@valeriu-PORTEGE-Z30-C:~$ ls -la esmvaltool_output/session-39cda3ae-7368-4e45-99ef-d7649845bfaf_20230804_121819/preproc/CMIP6_CESM2_fx_piControl_\*_areacella_gn/
total 1496
drwxrwxr-x 2 valeriu valeriu   4096 Aug  4 13:23 .
drwxrwxr-x 3 valeriu valeriu   4096 Aug  4 13:23 ..
-rw-rw-r-- 1 valeriu valeriu 250534 Aug  4 13:23 00_load.nc
-rw-rw-r-- 1 valeriu valeriu 250534 Aug  4 13:23 01_fix_metadata.nc
-rw-rw-r-- 1 valeriu valeriu 250534 Aug  4 13:23 02_concatenate.nc
-rw-rw-r-- 1 valeriu valeriu 250534 Aug  4 13:23 03_cmor_check_metadata.nc
-rw-rw-r-- 1 valeriu valeriu 250534 Aug  4 13:23 04_fix_data.nc
-rw-rw-r-- 1 valeriu valeriu 250534 Aug  4 13:23 05_cmor_check_data.nc
```

First off - I don't like this, am fairly sure users like Rebecca were not aware of such a behaviour - this is under the hood behaviour that may lead to problems (it is undocumented AFAIK, and such data output doesn't happen if one doesn't turn on intermediary saves), and second - @rebeccaherman1 please be advised of this and don't turn on intermediary saving. After a few runs from yesterday I ended up with my entire 120GB disk being full, and I was deleting old dockerr containers to make some room when all this time I had all these phantom session outputs :rofl:

**Comment by rebeccaherman1** [comment] 2023-08-04 16:02
@valeriupredoi thanks for pointing this out regarding the memory! (Did you mean to post it in your issue https://github.com/SciTools/iris/issues/5413 rather than as a followup here?)

And thank you for following through with the analysis looking for the bug. Just to double check -- is my understanding of the functions of `cell_methods`, `cell_measures`, and `ancillary_variables` now consistent with yours? Or is the concern that the cube intersection loses the data in another way?

Regarding a temporary fix -- it would indeed be appreciated @schlunma @sloosvel. I'm not rushing for a paper submission, but I have invested a fair amount of time now in trying to learn to use ESMValTool for data extraction, under the lasting belief that this is better for data availability and is or will be better for reproducibility. I was previously under the impression that I was extremely close to being able to actually start analyzing the data, and I am not eager to fall further behind by starting the data extraction again in some other framework. But if a temporary fix or workaround cannot be quickly found, I suppose I will go back to the Pangeo Project for the time being, or try to take advantage of the data on DKRZ directly using some structure other than cubes (though, in my experience, DataArrays and DataSets also have their own problems...).

**Comment by rebeccaherman1** [comment] 2023-08-04 16:37
> The loss of cell_measures and ancil vars is a direct effect of the intersection operation done by iris, none of our faults; we are just receiving the side effect of that issue by using cube.intersection in extract_region() - not a bug in that function that we can fix, we can write a workaround there, while iris folks figure out what's wrong at their end

Right -- I mean I wanted to check if it's really as disruptive as I thought to my data acquisition

> ouch, don't leave us just yet grin We'll try and get a workaround in soon +1

Oh dear -- I didn't mean that as a threat! I was just trying not to be too needy... but I really do want to get the data and move on :laughing:

**Comment by rebeccaherman1** [comment] 2023-08-07 11:29
I will work on bug-checking some following code and hope for an update soon :)

**Comment by valeriupredoi** [comment] 2023-08-07 11:40
we should probably patch extract_region with a temporary workaround very soon, will keep you in the loop - the thing with iris is that they will plop a bugfix but we don't know when and how long we'd have to wait for the release that contains it :+1:

**Comment by valeriupredoi** [comment] 2023-08-07 14:44
@rebeccaherman1 I have just patched extract_region with a workaround in https://github.com/ESMValGroup/ESMValCore/pull/2166 - you can use that branch for now, or use `main` branch when this will be merged; to use it you will have to install esmvalcore in development mode, have a look at the docs how to do it https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/install.html#installation-from-source and ping me if you're having troubles :beer:

**Comment by rebeccaherman1** [comment] 2023-08-08 09:03
Thank you so much!
I'll start working on installing developer mode, and I likely will ping you when I inevitably have trouble :beer:

**Comment by rebeccaherman1** [comment] 2023-08-08 14:10
@valeriupredoi I'm not sure if it's possible for me to install my own version of conda on DKRZ; is it necessary? 
I'm not very experienced at IT stuff like this; I downloaded a file to install conda and put in on DKRZ, but I believe that the hash check failed, and then I'm not sure what to do next.

**Comment by valeriupredoi** [comment] 2023-08-08 15:06
@rebeccaherman1 let us first finish the work in https://github.com/ESMValGroup/ESMValCore/pull/2166 and then I will create a sourceable environment for you on DKRZ

For dev installations: first you have to install ESMValTool in development mode, then, once that's done, and since that will still use a conda-forge (deployed/tagged) installation of ESMValCore, and since esmvalcore is a dependency of ESMValTool, you will have to install ESMValCore in development mode in the same conda environment, to be able to grab the latest `main` development branch of ESMValCore :+1:

**Closed** 2023-08-09 13:43 UTC
Labels: bug, bear at a dinner party

**Comment by valeriupredoi** [comment] 2023-08-09 14:50
@rebeccaherman1 now that we fixed that and merged in `main`, I have prepared a full development installation for you to use on DKRZ: please do `source /home/b/b382109/esmvaltool_environment_rebecca.sh` - it is important you do this without having any `PATH` variables set that point to any other Python installs, or that'll result in a dirty environment that's unpredictable; also don't module load the esmvaltool module after you've sourced that script, that script provides a self-consistent installation. Pls let me know if you have any problems :beer:

**Comment by rebeccaherman1** [comment] 2023-08-10 08:06
Thank you so much @valeriupredoi!

**Comment by rebeccaherman1** [comment] 2023-08-10 08:12
@valeriupredoi I'm getting a 'permission denied' error:
```bash
[b309244@levante3 ~]$ source /home/b/b382109/esmvaltool_environment_rebecca.sh
-bash: /home/b/b382109/esmvaltool_environment_rebecca.sh: Permission denied
```

Does it perhaps need to be moved into my working group?

**Comment by valeriupredoi** [comment] 2023-08-10 08:18
agh! Let me see about that - am not used to these different working groups DKRZ are using, I should have opened up my read and execute permissions on my `home` dir, can you pls check if you can list the contents of my $HOME with `ls -la /home/b/b382109` :beer:

**Comment by rebeccaherman1** [comment] 2023-08-10 08:20
I cannot list the contents of your $HOME:
```
[b309244@levante3 ~]$ ls -la /home/b/b382109
ls: cannot open directory '/home/b/b382109': Permission denied
```

**Comment by valeriupredoi** [comment] 2023-08-10 08:40
OK I've now 755-ed my entire home dir so in theory you should have read and execute permissions on any file I have there, but let me know if you still have troubles accessing files, since then we'll have to email DKRZ support and ask them to allow extra inter-group permissions that I can't set

**Comment by rebeccaherman1** [comment] 2023-08-10 08:47
OK I'm now able to access your directory and run the command without error, but I'm not sure what to do next. 
I was previously instructed to remove `conda` initialization from my `.bashrc` file so that I could create an environment and install other software as well (`tigrmaite`), and now I don't know how to use `conda` to create an environment without loading some python-based module. I believe this step was necessary because the `spack-levante/mambaforge...` file system was read-only.

**Comment by valeriupredoi** [comment] 2023-08-10 08:51
oh I didn't know you need to install extra packages in the environment - your Python is my Python now so you can use the full environment `rebecca` but you'll not be able to write to it, since I've not allowed write permissions; which Python package do you need? I can install it for you

**Comment by rebeccaherman1** [comment] 2023-08-10 08:54
Thanks, though that won't allow me to update it if I need (also in development mode there sometimes...). I need `tigramite`, which is best installed by cloning the directory and then running `python3 setup.py install`.

Perhaps there's some way for me to copy the environment you made for me over to my `$WORK` space and edit it there? Or would that not work?

**Comment by valeriupredoi** [comment] 2023-08-10 09:09
no that would not work because conda sets a bazillion paths in its system files, and those are absolute paths - I can install tigramite for you for now, but I think the best way forward in the long run is for you to install your esmvaltool/core in development mode, I can help you get that done :+1:

**Comment by valeriupredoi** [comment] 2023-08-10 09:14
is this the tigramite you need? https://github.com/jakobrunge/tigramite - it needs a set of dependencies that'll have to change in the env I created (nupy needs downgrading etc), this is why it's best if the package it and put it on conda-forge

**Comment by rebeccaherman1** [comment] 2023-08-10 11:36
> is this the tigramite you need? https://github.com/jakobrunge/tigramite

Yes, that's the one!

>it's best if the package it and put it on conda-forge

I'll try to bring that up with Jakob...

>I can install tigramite for you for now, but I think the best way forward in the long run is for you to install your esmvaltool/core in development mode, I can help you get that done :+1: 

Thank you so much! I really appreciate it.

**Comment by rebeccaherman1** [comment] 2023-08-10 12:53
Thanks so much -- I'll give it a try!

**Comment by rebeccaherman1** [comment] 2023-08-10 13:03
I think I need ipykernel in order to be able to use this environment in my jupyter notebook.

**Comment by valeriupredoi** [comment] 2023-08-10 13:17
installed :+1: 

```
(rebecca) [b382109@levante6 ~]$ conda list ipy
# packages in environment at /home/b/b382109/miniconda3/envs/rebecca:
#
# Name                    Version                   Build  Channel
ipykernel                 6.25.1             pyh71e2992_0    conda-forge
ipython                   8.14.0             pyh41d4057_0    conda-forge
```

**Comment by rebeccaherman1** [comment] 2023-08-10 13:47
@valeriupredoi I'm not sure what to make of it, but... using the kernel I made from the environment you made for me, I still lose the `cell_measures` and `ancillary_variables` upon extract region. Perhaps have I contaminated it somehow? :(

**Comment by rebeccaherman1** [comment] 2023-08-10 13:51
`/home/b/b382109/miniconda3/envs/rebecca/lib/python3.10/site-packages/esmvalcore/__init__.py`

**Comment by valeriupredoi** [comment] 2023-08-10 13:53
yes totally my bad, just detected the issue myself just now, just fixed it:
```
(rebecca) [b382109@levante6 ~]$ python -c "import esmvalcore; print(esmvalcore.__file__)"
/home/b/b382109/ESMValCore/esmvalcore/__init__.py
```

**Comment by rebeccaherman1** [comment] 2023-08-10 14:17
it works now! Thank you! :) :100:

**Comment by valeriupredoi** [comment] 2023-08-10 14:19
excellent news, cheers muchly @rebeccaherman1 :beers:

**Comment by rebeccaherman1** [comment] 2023-09-29 08:46
@valeriupredoi Would you be willing to help me set up the environment myself now?
I think I will shortly need to make some modifications to tigramite

**Comment by valeriupredoi** [comment] 2023-10-06 12:38
sure thing! Just follow the instructions at https://docs.esmvaltool.org/en/latest/quickstart/installation.html#install-from-source and ping me if you get stuck anywhere :+1:

**Comment by rebeccaherman1** [comment] 2023-10-06 13:39
@valeriupredoi Do I need to be in a particular branch for ESMValTool to get the development mode? Or master is fine?

**Comment by rebeccaherman1** [comment] 2023-10-06 14:12
Also @valeriupredoi How did you deal with getting python 3.10?

**Comment by valeriupredoi** [comment] 2023-10-06 14:40
no - you can use `main` no problems, but when you start developing stuff, and you'd like that to be added to ESMValTool (start contributing per se) that stuff needs to be on a development branch so you can open a pull request off it. For Python=3.10, change this line in environment.yml file `- python >=3.9` to `- python ==3.10` - that pins the Python version to 3.10 and will solve the environment with this version :+1:
