### ISSUE TITLE
Running with CMIP6 data and OBS data fails if using mip: AERmonZ

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#152] opened 2019-07-09 13:43 UTC
mirroring https://github.com/ESMValGroup/ESMValTool/issues/1208 for ESMValCore

**Comment by bouweandela** [comment] 2019-07-11 13:52
Duplicate of #160

**Closed by bouweandela** 2019-07-11 13:52 UTC
Labels: cmor, fix for dataset

**Comment by valeriupredoi** [comment] 2019-07-11 13:58
in case of issues that pertain to both Tool and Core we should make good practice to have both issues open/closed at the same time, no such thing as duplicates when dealing with two different projects

**Comment by bouweandela** [comment] 2019-07-11 14:03
Yes, but in this case it's an issue with the core only, as it's the preprocessor that fails.
