### ISSUE TITLE
New preprocessor mask_multimodel

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#487] opened 2020-02-13 15:15 UTC
**Is your feature request related to a problem? Please describe.**
I want to propagate the mask over several datasets such that when an element is masked in one dataset, it is also masked in all other datasets.

**Would you be able to help out?**
Yes, working on it. Initially I thought `mask_fillvalues` would do the job, but it doesn't. Also Github kindly points me to other issues, and just now I realize this has been discussed before here https://github.com/ESMValGroup/ESMValCore/issues/116

**Comment by mattiarighi** [comment] 2020-02-13 15:19
Can you be more specific on why `mask_fillvalues` doesn't do what you need.
From the feature request it looks like this is exactly what `mask_fillvalues` was designed for.

@valeriupredoi

**Comment by bascrezee** [comment] 2020-02-13 15:23
Yes, let me try to clarify.

```
datasets:
  - {dataset: cds-era5-monthly, type: reanaly, project: OBS, mip: Lmon,
     version: 1, tier: 3, start_year: 2008, end_year: 2010}
  - {dataset: CDS-SATELLITE-SOIL-MOISTURE, type: sat, project: OBS, mip: Lmon,
     version: COMBINED-TCDR-v201812.0.0, tier: 3, start_year: 2008, end_year: 2010}

preprocessors:
  test_b:
    regrid:
      target_grid: 0.25x0.25
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.00    # keep all missing values
      min_value: -1e+20           # small enough not to alter the data
```

In my diagnostic script:
```
def _get_cubelist(cfg):
    input_data = cfg['input_data'].values()
    grouped_input_data = group_metadata(
        input_data, 'dataset', sort='dataset')
    cubes = []
    for datasetname in grouped_input_data.keys():
        cubes.append(iris.load_cube(grouped_input_data[datasetname][0]['filename']))
    return iris.cube.CubeList(cubes)


def main(cfg):
    """Calculate linear regression between albedo and xxfrac.

    Arguments:
    ---------
        cfg - nested dictionary of metadata
    """
    cubelist = _get_cubelist(cfg)
    assert(np.array_equal(cubelist[0].data.mask, cubelist[1].data.mask))
```

Executing raises `AssertionError`

**Comment by mattiarighi** [comment] 2020-02-13 15:25
Maybe we should try to extend or adapt `mask_fillvalues` rather than create a new preprocessor.
@valeriupredoi any suggestion?

**Comment by bascrezee** [comment] 2020-02-13 15:29
Yes, I would be in favour of that as well. There is another tiny bug in mask_fillvalues as well, let's fix that first (working on it).

**Comment by valeriupredoi** [comment] 2020-02-13 15:41
@bascrezee can you post the output of `np.where((cubelist[0].data.mask ^ cubelist[1].data.mask) is True)` pliz :beer:

**Comment by valeriupredoi** [comment] 2020-02-13 15:44
there is no actual reason why to implement a new preproc func for this - it should work as it is now for exactly this purpose, unless, of course, there is a bug that I have not seen so far (totally possible)

**Comment by valeriupredoi** [comment] 2020-02-13 15:57
also I think I know where your assertion error comes from - if you have time axes with different dimesnions, then the assertion error will come up - try `assert(np.array_equal(cubelist[0][0].data.mask, cubelist[1][0].data.mask))`

**Comment by bascrezee** [comment] 2020-02-13 16:00
Thanks for the super fast support guys. Have to leave now, I will look further into this tomorrow.

**Comment by bascrezee** [comment] 2020-02-14 09:42
```
    # Check if the masks are exactly equal
    a = cubelist[0].data.mask
    b = cubelist[1].data.mask

    print("Check 1 as requested by V: ")
    print(np.where((a ^ b) is True))
    print("Check 2: ")
    print((a==b).all())
    print("Check 3: ")
    print(np.array_equal(a,b))
```

```
Check 1 as requested by V:
(array([], dtype=int64),)
Check 2:
False
Check 3:
False
```

So the arrays are not equal in my use case, and indeed I could trace it to a slightly differing time axis (1 day shifted) as suggested by @valeriupredoi.

**Comment by valeriupredoi** [comment] 2020-02-14 09:46
Phew, so our jood old method is still accurate then :beer

**Comment by valeriupredoi** [comment] 2020-02-14 09:47
Sorry, pressed the wrong button on my phone. Cheers, so the method is still accurate phew :beer:

**Comment by valeriupredoi** [comment] 2020-02-14 11:41
can close this @bascrezee no? :beer:

**Comment by schlunma** [comment] 2020-08-18 15:51
I tried to implement the feature that @bascrezee describes in this issue (apply a common mask to all datasets) with this recipe (also following [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#common-mask-for-multiple-models) section of the documentation).

```yaml
---
documentation:
  description: |
    test.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references: []

  projects:
    - crescendo


preprocessors:

  preproc:
    regrid:
      target_grid: 5x5
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.0
      min_value: -1e20


diagnostics:

  diag_test:
    variables:
      tas:
        project: CMIP6
        exp: historical
        preprocessor: preproc
        mip: Amon
        start_year: 2005
        end_year: 2005
        var_type: feature
        additional_datasets:
          - {dataset: HadCRUT4, short_name: tas, project: OBS, type: ground, version: '1', tier: 2}
          - {dataset: BCC-CSM2-MR, ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```

However, the preprocessed files do not have the same mask:

**GitHub does not let me insert a png right now, I will upload it tomorrow**

Can someone tell what the correct settings for `mask_fillvalues` are to simply get a common mask? I also vote strongly for adding the suggested preprocessor `mask_multimodel`. To be honest, I do not completely understand the different parameters used in `mask_fillvalues`, so a simple wrapper for this might be helpful.

**Comment by schlunma** [comment] 2020-08-18 15:52
I tried to implement the feature that @bascrezee describes in this issue (apply a common mask to all datasets) with this recipe (also following [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#common-mask-for-multiple-models) section of the documentation).

```yaml
---
documentation:
  description: |
    test.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references: []

  projects:
    - crescendo


preprocessors:

  preproc:
    regrid:
      target_grid: 5x5
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.0
      min_value: -1e20


diagnostics:

  diag_test:
    variables:
      tas:
        project: CMIP6
        exp: historical
        preprocessor: preproc
        mip: Amon
        start_year: 2005
        end_year: 2005
        var_type: feature
        additional_datasets:
          - {dataset: HadCRUT4, short_name: tas, project: OBS, type: ground, version: '1', tier: 2}
          - {dataset: BCC-CSM2-MR, ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```

However, the preprocessed files do not have the same mask:

**GitHub does not let me insert a png right now, I will upload it tomorrow**

Can someone tell what the correct settings for `mask_fillvalues` are to simply get a common mask? I also vote strongly for adding the suggested preprocessor `mask_multimodel`. To be honest, I do not completely understand the different parameters used in `mask_fillvalues`, so a simple wrapper for this might be helpful.

**Comment by schlunma** [comment] 2020-08-18 15:52
I tried to implement the feature that @bascrezee describes in this issue (apply a common mask to all datasets) with this recipe (also following [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#common-mask-for-multiple-models) section of the documentation).

```yaml
---
documentation:
  description: |
    test.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references: []

  projects:
    - crescendo


preprocessors:

  preproc:
    regrid:
      target_grid: 5x5
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.0
      min_value: -1e20


diagnostics:

  diag_test:
    variables:
      tas:
        project: CMIP6
        exp: historical
        preprocessor: preproc
        mip: Amon
        start_year: 2005
        end_year: 2005
        var_type: feature
        additional_datasets:
          - {dataset: HadCRUT4, short_name: tas, project: OBS, type: ground, version: '1', tier: 2}
          - {dataset: BCC-CSM2-MR, ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```

However, the preprocessed files do not have the same mask:

**GitHub does not let me insert a png right now, I will upload it tomorrow**

Can someone tell what the correct settings for `mask_fillvalues` are to simply get a common mask? I also vote strongly for adding the suggested preprocessor `mask_multimodel`. To be honest, I do not completely understand the different parameters used in `mask_fillvalues`, so a simple wrapper for this might be helpful.

**Comment by schlunma** [comment] 2020-08-20 15:23
I'm now fairly sure that I know what's going on here.

Lets assume we have cubes with the dimensions `(TIME, LAT, LON)`. Then the preprocessor `mask_fillvalues` produces a common mask with the dimension `(LAT, LON)`, since it collapses over the time dimension during the mask calculation:

https://github.com/ESMValGroup/ESMValCore/blob/594cb65498f92e6c08586e86d05933538be09de1/esmvalcore/preprocessor/_mask.py#L642-L652

Thus, this preprocessor is **not** able to produce a time-dependent mask. However, the HadCRUT4 dataset's mask varies from month to month. For the settings given in the recipe above (`treshold_fraction=0.0` and `min_value=-1e20`), the mask produced by `mask_fillvalues` masks only points where every month contains a missing value; if a single month contains data and the 11 others don't then the point is not masked. This mask is shown in the left plot above for the first month, but the mask of all other months are identical (this is model data which originally has no missing values).

The right plot however shows the first month of the HadCRUT4 dataset. The mask contains more missing values than the common mask since there are points with additional missing values in this first month which are not missing for other months. In contrast to the common mask, the mask of HadCRUT4 is time-dependent and varies from month to month.

For different settings (`treshold_fraction=1.0` and `min_value=-1e20`), `mask_fillvalues` does indeed produce an identical mask for all datasets. However, this is not time-dependent and cuts all points for HadCRUT4 where at least a single month as missing values:

![Screenshot_20200820_170144](https://user-images.githubusercontent.com/32543114/90789477-40d1f800-e307-11ea-9ab0-2c63110e99c1.png)

This is not what I would except from a true `mask_multimodel` preprocessor that produces a common mask. It should not distinguish between the different dimensions by treating the time dimension in a special way. For the datasets mentioned above, the preprocessor should apply the time-dependent HadCRUT4 mask to all CMIP6 datasets (which originally do not have missing values).

Moreover, I think that there is a bug concerning the `min_value` parameter: If `min_value` is not given, the [documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#missing-values-masks) states that the original mask of the dataset is used. However, following this line this is not always true:

https://github.com/ESMValGroup/ESMValCore/blob/594cb65498f92e6c08586e86d05933538be09de1/esmvalcore/preprocessor/_mask.py#L408-L411

If the data randomly contains a zero, then it is additionally masked. I think line 409 should be something like this:


```python
data_hits = np.ones_like(data)
```

**Comment by bascrezee** [comment] 2020-09-01 08:56
> This is not what I would except from a true mask_multimodel preprocessor that produces a common mask. It should not distinguish between the different dimensions by treating the time dimension in a special way. For the datasets mentioned above, the preprocessor should apply the time-dependent HadCRUT4 mask to all CMIP6 datasets (which originally do not have missing values).

I fully agree. I saw you already started a branch, is it ready for a PR?

**Comment by schlunma** [comment] 2020-09-01 16:19
I opened a draft PR (#767), but several things are missing which I listed in this PR. Any contributions to this are welcome since I probably will not have the time to finish this soon!

**Comment by Peter9192** [comment] 2020-09-10 09:53
I see how this is different from mask_fillvalues. I wonder if it should replace [mask_fillvalues for multiple models](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html#common-mask-for-multiple-models) altogether? If not, at least the documentation should clarify what the difference is between the two.

**Comment by bascrezee** [comment] 2020-10-20 12:00
I like the naming 'mask_multimodel' as it currently is in https://github.com/ESMValGroup/ESMValCore/pull/767. It clearly tells what this preprocessor is about. I think the section "Common mask for multiple models" in the documentation should be replaced by a section using the new preprocessor 'mask_multimodel' instead.

**Closed** 2021-03-18 16:29 UTC
Labels: enhancement, preprocessor
