### ISSUE TITLE
Fix iris (>2) warnings

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#127] opened 2019-02-13 12:32 UTC
Since we will switch to iris 2 very soon now (at least I hope so :grin:), it would be nice to address warnings which still appear in the new version. I will list some of them which regularly appear in my runs, but this is definitely not a complete list. Anyone is invited to add further items.

- [x]  `/iris/coords.py:1355: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'year'.`
This warning appears when the `time` coordinate is collapsed. The reason are the temporal `AuxCoords` `year`, `day_of_year`, etc. which do not have bounds (which makes sense), so it would be best to disable this warning for those certain coordinates. It also appears when any other coordinate without bounds is collapsed.

- [x] `/numpy/ma/core.py:3174: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use arr[tuple(seq)] instead of arr[seq]. In the future this will be interpreted as an array index, arr[np.array(seq)], which will result either in an error or a different result.`
This appears somewhere in the iris code (I do not know exactly where) and should probably be fixed by iris itself. *edit* This one will be fixed in the next Iris release: https://github.com/SciTools/iris/pull/3212#issuecomment-510095803

- [x] `iris/fileformats/cf.py:798: UserWarning: Missing CF-netCDF measure variable 'areacella', referenced by netCDF variable 'tas'`
Warnings like this appear very often in the preprocessor. Most likely it's because of the `cell_measures` attribute in the raw cubes (e.g. `tas:cell_measures = "area: areacella"`). Would it break something if we removed this attribute?

- [ ] `iris/__init__.py:237: IrisDeprecation: setting the 'Future' property 'cell_datetime_objects' is deprecated and will be removed in a future release. Please remove code that sets this property.`
This should be solved by removing the appearances of this property in the code (in `esmvaltool/cmor/check.py` and `esmvaltool/diag_scripts/autoassess/stratosphere/strat_metrics_1.py`).

- [ ] `iris/analysis/cartography.py:394: UserWarning: Using DEFAULT_SPHERICAL_EARTH_RADIUS.`
This appears when grid cell areas are calculated by `iris.analysis.cartography.area_weights`. The warning does not appear if the Earth radius is specified in the cube. Alternatively, we could use the fx_files to calculate areas.

Not iris warnings, but still appear very often:

- [ ] `WARNING There were warnings in variable nbp: nbp: attribute positive not present`
This appears for almost every CMIP5 model with this attribute, so in my opinion we should either disable this warning completely or demote it to a debug message. Another possibility would be to add it automatically during the CMOR check.

I think these are the most frequent ones and it should not be too hard to get rid of them.

**Comment by bascrezee** [comment] 2019-07-10 11:24
```/numpy/ma/core.py:3174: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use arr[tuple(seq)] instead of arr[seq]. In the future this will be interpreted as an array index, arr[np.array(seq)], which will result either in an error or a different result.```

Some additional information on this warning, that you reported already.  I also came across it while working on:  https://github.com/ESMValGroup/ESMValTool/pull/1200
This warning can be reproduced easily like this (taken from [Stackoverflow](https://stackoverflow.com/questions/52110869/futurewarning-using-a-non-tuple-sequence-for-multidimensional-indexing-is-depre) )
```
x = np.zeros((4,2))
x[slice(None),1]    # works
x[[slice(None),1]]  # raises Warning
```

Has this one been reported to Iris already? @bjlittle

**Comment by bjlittle** [comment] 2019-07-10 12:09
@schlunma What versions of `iris` and `numpy` are you guys using?

I'm looking to re-haul the amount of warnings that `iris` generates, which is over verbose as far as I'm concerned.

**Comment by schlunma** [comment] 2019-07-10 12:37
Right now I'm using `numpy 1.16.4` and `iris 2.2.1`, but I suppose this has changed since I initially created this issue.

**Comment by bascrezee** [comment] 2019-07-19 08:12
> Warnings like this appear very often in the preprocessor. Most likely it's because of the cell_measures attribute in the raw cubes (e.g. tas:cell_measures = "area: areacella"). Would it break something if we removed this attribute?

@bouweandela what do you think? Removing this attribute? Or maybe filtering out the warnings at the top level (is that possible?), since according to @schlunma ESMValTool is designed like this on purpose and the warning is therefore not relevant at any level within ESMValTool. Is that correct?

**Comment by bouweandela** [comment] 2019-07-19 12:20
@bjlittle is planning to build support for it into `iris`, see https://github.com/SciTools/iris/issues/3329. If that works out, the solution should be as simple as loading both files at the same time:
the solution is not as easy as loading both files at the same time:
```python
>>> import iris
>>> iris.load(["/badc/cmip5/data/cmip5/output1/BCC/bcc-csm1-1/historical/fx/atmos/fx/r0i0p0/latest/areacella/areacella_fx_bcc-csm1-1_historical_r0i0p0.nc", "/badc/cmip5/data/cmip5/output1/BCC/bcc-csm1-1/historical/mon/atmos/Amon/r1i1p1/latest/tas/tas_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc"])
/group_workspaces/jasmin2/cp4cds1/magic-test/tmp-bandela/version2_development/conda/envs/esmvaltool/lib/python3.6/site-packages/iris/fileformats/cf.py:798: UserWarning: Missing CF-netCDF measure variable 'areacella', referenced by netCDF variable 'tas'
  warnings.warn(message % (variable_name, nc_var_name))
[<iris 'Cube' of air_temperature / (K) (time: 1956; latitude: 64; longitude: 128)>,
<iris 'Cube' of cell_area / (m2) (latitude: 64; longitude: 128)>]
```
(note that this currently does not work yet).

**Comment by stefsmeets** [comment] 2020-10-29 09:29
Is this still relevant when we are now working on iris3? #378 #819

**Comment by zklaus** [comment] 2021-05-27 15:54
I think this issue is obsolete now; closing. @schlunma, please reopen if you feel otherwise.

**Closed by zklaus** 2021-05-27 15:54 UTC
Labels: enhancement

**Comment by bjlittle** [comment] 2021-06-08 05:56
BTW we're going to be moving to `logging` for `iris` 3.1, which will silence, finally, all/most of the warning messages :+1:

**Comment by zklaus** [comment] 2021-06-08 11:01
Cheers for the heads-up, @bjlittle
