### ISSUE TITLE
Optimization needed for regrid (including esmpy) and level selection

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#775] opened 2020-09-10 14:24 UTC
This is an amalgamation of multiple issues that were open at separate times, initially believed to be caused by other problems; issues closed and squashed in here #724 #774 and draft PR #773 ; in short:

- regridding large 3d datasets (like ocean data) takes a long time; this is not due to poor implementation but rather it is the limit of any serial run w/o parallelization; @bouweandela has implemented lazy regridding that will be available in `iris` (well done man!) but that will not make things much faster if we don't parallelize the regridding at least on vertical levels;
- level selection currently consumes a lot of memory - it is not lazy and is done via loading the full data object into memory several times, as many levels there are;

I think we need to start thinking about this and talk about it; I have already tried to parallelize the esmpy 3d regridding but it's difficult due to the amount of complexity that needs to be passed to the parallel process. Anyway, I will have a look at the level selection imminently, but for now this is a placeholder for @rswamina @omeuriot @ledm and others working on ocean data that things will improve, just bear with us :beer:

**Comment by valeriupredoi** [comment] 2020-09-11 10:07
@bouweandela `_vertical_interpolate()` is not:
```python
    if np.any(mask):
        # Ensure that the data is masked appropriately.
        new_data = np.ma.array(new_data, mask=mask, fill_value=_MDI)

    # Construct the resulting cube with the interpolated data.
    return _create_cube(cube, new_data, src_levels, levels.astype(float))
```

**Comment by valeriupredoi** [comment] 2020-09-11 10:12
also that function keeps two copies of the data from `cube.data` and `new_data` which are of similar sizes and dereferencing happens only at the very end so they stay in memory

**Comment by valeriupredoi** [comment] 2020-09-11 13:03
OK partially addressed memory issue from `vertical_interpolate` in #776 (saving about 30% memory) but the main problem is `stratify` gets all the stuff done unlazied, did we have a fix to remove stratify? :beer:

**Comment by bouweandela** [comment] 2020-09-25 14:09
Some time ago, I tried to use ESMPy with the function [dask.array.map_blocks](https://docs.dask.org/en/latest/array-api.html#dask.array.map_blocks) to make regridding for grids with 2D latitude/longitude coordinates lazy, but the problem is that ESMPy cannot be used from multiple Python threads.

Here is a fairly minimal example demonstrating the problem:
```python
import threading

import ESMF
import numpy as np


def run():
    ESMF.Grid(np.array((10, 20)),
              num_peri_dims=1,
              staggerloc=[ESMF.StaggerLoc.CENTER])


def main():

    ESMF.Manager(debug=True)

    run()

    thread = threading.Thread(target=run)
    thread.start()
    thread.join()


if __name__ == '__main__':
    main()
```
running this results in the following stack trace:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test_esmf_threading.py", line 8, in run
    ESMF.Grid(np.array((10, 20)),
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/site-packages/ESMF/util/decorators.py", line 64, in new_func
    return func(*args, **kwargs)
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/site-packages/ESMF/api/grid.py", line 389, in __init__
    self._struct = ESMP_GridCreate1PeriDim(self.max_index,
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/site-packages/ESMF/interface/cbindings.py", line 507, in ESMP_GridCreate1PeriDim
    raise ValueError('ESMC_GridCreate() failed with rc = '+str(rc)+'.    '+
ValueError: ESMC_GridCreate() failed with rc = 545.    Please check the log files (named "*ESMF_LogFile").
```
and the content of the file `PET0.ESMF_LogFile` is:
```
20200925 160635.455 INFO             PET0 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
20200925 160635.455 INFO             PET0 !!! THE ESMF_LOG IS SET TO OUTPUT ALL LOG MESSAGES !!!
20200925 160635.455 INFO             PET0 !!!     THIS MAY CAUSE SLOWDOWN IN PERFORMANCE     !!!
20200925 160635.455 INFO             PET0 !!! FOR PRODUCTION RUNS, USE:                      !!!
20200925 160635.455 INFO             PET0 !!!                   ESMF_LOGKIND_Multi_On_Error  !!!
20200925 160635.455 INFO             PET0 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
20200925 160635.455 INFO             PET0 Running with ESMF Version   : 8.0.0
20200925 160635.455 INFO             PET0 ESMF library build date/time: "Mar 31 2020" "06:07:20"
20200925 160635.455 INFO             PET0 ESMF library build location : /home/conda/feedstock_root/build_artifacts/esmf_1585634161154/work
20200925 160635.455 INFO             PET0 ESMF_COMM                   : mpich3
20200925 160635.455 INFO             PET0 ESMF_NETCDF                 : enabled
20200925 160635.455 INFO             PET0 ESMF_PNETCDF                : disabled
20200925 160635.455 INFO             PET0 ESMF_PIO                    : enabled
20200925 160635.455 INFO             PET0 ESMF_YAMLCPP                : enabled
20200925 160635.455 INFO             PET0 ESMF_MOAB                   : enabled
20200925 160635.456 ERROR            PET0 ESMCI_VM.C:1809 ESMCI::VM::getCurrent() Internal error: Bad condition  - - Could not determine current VM
20200925 160635.456 ERROR            PET0 ESMCI_VM_F.C:1056 c_esmc_vmgetcurrent() Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.456 ERROR            PET0 ESMF_VM.F90:5074 ESMF_VMGetCurrent() Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.456 ERROR            PET0 ESMF_Grid.F90:29232 ESMF_GridCreateDistgridReg Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.456 ERROR            PET0 ESMF_Grid.F90:9203 ESMF_GridCreate1PeriDimR Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.456 ERROR            PET0 ESMF_Grid_C.F90:236 f_esmf_gridcreate1peridim Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.456 ERROR            PET0 ESMCI_Grid.C:344 ESMCI::Grid::create1peridim() Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.456 ERROR            PET0 ESMC_Grid.C:118 ESMC_GridCreate1PeriDim() Internal error: Bad condition  - Internal subroutine call returned Error
20200925 160635.457 INFO             PET0 Finalizing ESMF
```

**Comment by bouweandela** [comment] 2020-09-25 20:08
It would be interesting to see if we can use [xESMF](https://xesmf.readthedocs.io) instead of our own solution. They work around the above problem by only using ESMF to build a sparse matrix with weights to define the regridder and then the actual regrid step, where you need to use multiple threads for the different chunks in the dask array, is just matrix multiplication using scipy.

**Comment by valeriupredoi** [comment] 2020-09-29 11:31
@bouweandela how about `mpi4py`?

**Comment by valeriupredoi** [comment] 2020-09-29 11:48
at the bottom of this [page](http://www.earthsystemmodeling.org/esmf_releases/last_built/esmpy_doc/html/examples.html) there is an example how to run esmpy with mpi4py - looks nifty - but unfortunately I don't know much about esmpy/esmf to be able to say it'll work for us

**Comment by rswamina** [comment] 2020-11-10 13:33
@valeriupredoi : I still get a Memory Error when I run the example recipe I shared in (https://github.com/ESMValGroup/ESMValCore/issues/774). I am running this on the JASMIN sci3 machine and with ESMValTool and ESMValCore versiosn both at 2.1.0. Should I do anything different?

**Comment by valeriupredoi** [comment] 2020-11-11 11:16
@rswamina I ran the recipe in #774 in about 5min on jasmin@sci3 with max RES memory at about 21G with `max_parallel_tasks = 1` in config-user - note that if you have `max_parallel_tasks` set to a high number in config-user, you will blow up the memory, but in the case of that particular recipe you only have one task anyway, so no need to worry. Can you pls post the error message you get from running it? :beer:

**Comment by rswamina** [comment] 2020-11-11 12:28
@valeriupredoi : Apologies..I should have clarified that this is a problem when I increase the number of years. I dug into this a bit as well and it seems that what we discussed in the meeting last week was that there would be some improvement. If I am to run this for 500 years instead of the 10 I would have to wait for the updates with iris etc to be made? Here is the changed version where I ran out of memory:

```
- {dataset: UKESM1-0-LL, exp: piControl, start_year: 1960, end_year: 2459, grid: gn, ensemble: r1i1p1f2 }
- {dataset: IPSL-CM6A-LR, exp: piControl, start_year: 1850, end_year: 2349, grid: gn, ensemble: r1i1p1f1 }
- {dataset: MRI-ESM2-0, exp: piControl,  ensemble: r1i1p1f1,  start_year: 1860,  end_year: 2349, grid: gn}
```
It would be good to know if I am doing something wrong or if this issue needs fixing as planned so I can make other arrangements to run my jobs for the present.

**Comment by bouweandela** [comment] 2020-11-11 14:19
A lazy regridder for ocean data (data with 2D lat/lon coordinates) is under development in this repository: https://github.com/SciTools-incubator/iris-esmf-regrid. Once it is in a condition where it can be used, we can start using it with the ESMValCore and regridding ocean data should require much less memory.

**Comment by valeriupredoi** [comment] 2020-11-11 15:19
@rswamina there is no way in .. ahem..Four Seasons Total Landscaping that you can run 500 years on any node - the recipe in #774 with the datasets you gave me each for 100 years:
```
2020-11-11 14:40:03,194 UTC [26411] INFO    Time for running the recipe was: 1:45:23.164513
2020-11-11 14:40:03,900 UTC [26411] INFO    Maximum memory used (estimate): 204.1 GB
```
So for 500 years you would need 1000GB :rofl: Maybe you can run in 100yrs chunks? Note that what @bouweandela refers to will improve the memory footprint, but it will be still slow as a Monday since we have not parallelized irregular regridding :beer:

**Comment by bouweandela** [comment] 2020-11-11 15:29
As an (ugly) workaround, you can probably just define several variable groups in the recipe, if you then run the recipe with `max_parallel_tasks: 1` it should work (if you also make sure to load all preprocessed files with the same `short_name` and `dataset` value into a single cube in the diagnostic).

```yaml
    variables:
      thetao_1960_2000: &var
        short_name: thetao
        preprocessor: preproc_zonal_ocean
        project: CMIP6
        mip: Omon
        start_year: 1960
        end_year: 2000
      thetao_2000_2050:
        <<: *var
        start_year: 2000
        end_year: 2050
      thetao_2050_2100:
        <<: *var
        start_year: 2050
        end_year: 2100   
      ... etc until 2349
```

**Comment by valeriupredoi** [comment] 2020-11-11 15:45
I like how @bouweandela thinks - the old problem that shows two medium pizzas are smaller together than a large pizza :pizza:

**Comment by rswamina** [comment] 2020-11-11 15:53
@bouweandela and @valeriupredoi : Thanks for the suggestions. I tried something similar to @bouweandela's suggestion but this is better. I will use this. I must admit I am surprised that this issue of processing pi-ctrl data has not risen before. Have I just missed this?I am happy to report progress here when I finish with this. Thanks again!

**Comment by bouweandela** [comment] 2020-11-11 16:30
> Have I just missed this?

We've known for ages that the tool cannot process large datasets, but it just takes time for this to 1) become the most important problem and then 2) actually solve the problem.

**Comment by rswamina** [comment] 2020-11-24 11:30
Just a note that I was able to split the years and run my recipe. This is not the most elegant solution though, mainly because different models use different start and end years for pi-control runs. You end up having a whole host of these min-datasets in the recipe.

**Comment by zklaus** [comment] 2020-11-24 14:12
The main issue of excessive memory consumption and non-laziness in the irregular regridding will be addressed by SciTools-incubator/iris-esmf-regrid. Do we need to keep this issue around? Are there other aspects that should be addressed independently?

**Comment by valeriupredoi** [comment] 2020-11-24 15:41
cheers @zklaus and good you managed to get some sort of run done @rswamina :+1: Yes, let's keep the issue open as a placeholder for the performance issue, hopefully we will close it with the advent of the new iris, but until then it shows we're preoccupied :grinning:

**Comment by schlunma** [comment] 2023-07-14 13:57
iris-esmf-regrid is now fully available using [generic regridding schemes](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#generic-regridding-schemes), and stratify is [lazy](https://github.com/SciTools/python-stratify/pull/52).

There are remaining issues with `extract_levels`, but these are handled in dedicated issues (#2114, #2121). Please re-open if necessary.

**Closed by schlunma** 2023-07-14 13:57 UTC
Labels: enhancement, preprocessor
