### ISSUE TITLE
On using "convert_units" preprocessor, units in configuration file not changed

### ISSUE THREAD

**Issue by bettina-gier** [ESMValGroup/ESMValCore#866] opened 2020-11-19 15:32 UTC
when using the convert_units preprocessor, the units in both the "metadata.yml", as well as "var_info.ncl" are kept as the cmor units, while the data fed to the diagnostics has different units. I feel like the updated units due to the preprocessor should be reflected, especially as I wanted to used the units attribute from these file for my plots, and I feel this may be a common occurence?

**Comment by nielsdrost** [comment] 2020-11-25 10:50
Perhaps @jvegasbsc knows? :-)

**Comment by jvegasbsc** [comment] 2020-11-25 11:10
Good catch! I am not sure how to proceed: the correct units are on the file, the `var_info` contains the original info. I think we should not change that info during the preprocessor, but I am not really sure. The safest way will be to read the `units` attribute from the NetCDF file and use this.

By the way, you opened Pandora's box here, as we are not taking this into account in any preproc function, and even some of them don't produce the correct units. A couple of examples:

- We are not changing them from `mm day-1` to `mm yr-1` when doing a yearly sum on `pr`
- We are not changing them from `whatever m-2` to `whatever` when doing area sums

**Comment by bettina-gier** [comment] 2020-11-25 11:21
Right, I'll use the units from the file then. Ideally I suppose you would have an "original units" attribute for the cmor info and then a "preproc units" for anything that the preprocessor did to it, though I can see how that might be hard to do. In this case at least the netcdf file has the correct attributes, while I guess the sums you mentioned above do not.

**Comment by bouweandela** [comment] 2020-12-22 12:27
The original issue, as reported by @bettina-gier is a duplicate of #505. The issues reported by @jvegasbsc should probably be made into new issues.

**Comment by znicholls** [comment] 2022-06-06 15:13
> * We are not changing them from `whatever m-2` to `whatever` when doing area sums

Made a specific issue for this here: https://github.com/ESMValGroup/ESMValCore/issues/1613

**Closed** 2022-11-07 10:03 UTC
Labels: cmor
