### ISSUE TITLE
`fix_metadata` sometimes only works in serial (at least) for CMIP3

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1247] opened 2021-07-21 14:35 UTC
**Describe the bug**
The `fix_metadata` preprocessor step can hang if executed in parallel on CMIP3 data. This is illustrated in `recipe_bock20jgr.yml`.

**Comment by bouweandela** [comment] 2021-09-30 17:58
This looks like a duplicate of #430

**Comment by schlunma** [comment] 2022-02-04 11:23
Moving this to v2.6 since there is not open PR yet.

**Comment by bouweandela** [comment] 2022-05-30 09:09
Closing this because it is a duplicate.

**Closed by bouweandela** 2022-05-30 09:09 UTC
