### ISSUE TITLE
Presence of ancillary vars breaks multi-model statistics step

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1213] opened 2021-07-06 11:38 UTC
**Describe the bug**
Due to the recent updates in both the handling of fx variables and the multimodel statistics preprocessor, there appear issues when combining these two steps. Because some models might not have fx files available, and therefore some cubes will not have ancillary variables or cell measures, maybe the multimodel statistics step should check their presence and remove them before computing the statistics.

**Comment by zklaus** [comment] 2021-07-06 12:25
Thanks for opening the issue! Before moving to how to address this issue ("maybe remove..."), let's try to clarify a bit more.

What variables are we talking about? Is there a material difference between `cell_measures` and `ancillary_variables`? Could averaging or another approach be reasonable?

Since the grids and coordinates need to be the same for the multi-model statistics anyway, at least most `cell_measures` should be the same as well (they are measures of the cell, after all), so perhaps averaging them or making sure that they agree where present could be the best way to handle this?

**Comment by zklaus** [comment] 2021-07-07 10:15
This seems to be the toughest nut to crack right now. @bouweandela, @Peter9192, do you have some insight or ideas?

**Comment by Peter9192** [comment] 2021-07-07 10:36
> This seems to be the toughest nut to crack right now. @bouweandela, @Peter9192, do you have some insight or ideas?

A minimal use case that triggers this problem might help...

**Comment by sloosvel** [comment] 2021-07-07 10:36
I proposed to remove it because fx vars are not always present.  If you compute an statistic 10 datasets and only 2 of them have ancillary vars, the result would be a cube with data from 10 datasets and an average ancillary var with data from 2 of them. 

I am not sure if there are significant differences in those variables from model to model, or if that would make this approximation be a source of large differences. 

If they give grid information and all of them are in the same grid then I would say it's not a big deal, but maybe it's something that would bother scientists. I once had someone concerned about relative differences  of 0.01% in an area, so I guess it depends on how picky you are.

**Comment by bouweandela** [comment] 2021-07-07 11:02
I agree with @sloosvel that it might be difficult to come up with reasonable values and I also feel that coming up with reasonable values for the computed statistics is a new feature that could be worked on later. However, the current position of the multimodel statistics preprocessor function in the default order is before the statistics functions that use cell measures: https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/preprocessor/__init__.py#L137. Is there a reason to first compute the multimodel statistics and then the other statistics? Computationally it would be much more efficient to move this to after area/volume/time statistics. That would probably also be more accurate, because if you do the area average with the cell areas before the multimodel statistics, there is no need to regrid and use guessed cell areas on the multimodel statistics cube.

**Comment by bouweandela** [comment] 2021-07-07 13:56
To explain the above a bit more clearly, here are some examples of preprocessing chains that users could build:

Current implementation:
* 2D input -> regrid -> multimodel stats -> area stats
* 3D input -> extract levels -> regrid -> multimodel stats -> volume stats
* daily input -> multimodel stats (fails because of 360 day + 365 day calendars) -> monthly statistics

Whereas if we would move multimodel stats to the end, the above examples would simplify to
* 2D input -> area stats -> multimodel stats
* 3D input -> volume stats -> multimodel stats
* daily input -> monthly statistics -> multimodel stats (works because all calendars have 12 months)

so we would loose the regrid and extract levels functions that introduce inaccuracies.

**Comment by zklaus** [comment] 2021-07-07 14:33
Thanks, @bouweandela, that makes sense to me.

As for coming up with reasonable values, I am not so sure this will be difficult after all. @tomaslovato made an interesting comment about this: https://github.com/ESMValGroup/ESMValCore/issues/1189#issuecomment-874742702.
To my mind, there are `cell_measures`, i.e. measures of the cells that reflect intrinsic properties of the cells that must be the same for all participating datasets because the grid and with it all its cells must be the same. And then there are other variables such as orography and land area fraction, where imho averaging is meaningful.
But I think this deserves more deliberation and may well be counted as a new feature, so I suggest tackling that at the earliest for 2.4.0 and go with the changed order plus removal of these data in the multi-model preprocessor for now.

@ESMValGroup/esmvaltool-developmentteam is anyone opposed to changing the preprocessor order as described by @bouweandela ?

@Peter9192, sorry to dump this much work on your desk, but would you mind tackling the removal of ancillary variables and cell measures in the multi-model statistics? Please do let me know if this is beyond your availability right now!

**Comment by zklaus** [comment] 2021-07-07 14:50
One comment that shows the problem is https://github.com/ESMValGroup/ESMValTool/issues/2198#issuecomment-863238983.

**Comment by Peter9192** [comment] 2021-07-07 14:58
I'm sorry, but I really don't have a lot of time for this. It sounds quite straightforward, but most of the time for me would be in setting up the test case that the new fix should be able to pass. If someone could go ahead and write a test (similar to what I've done [here](https://github.com/ESMValGroup/ESMValCore/pull/1209/commits/36fbe7ab883dac220dfd91b6b24eb5aaaf63bd15)), then I might be able to commit a fix to that branch.

**Comment by katjaweigel** [comment] 2021-07-08 08:16
> To explain the above a bit more clearly, here are some examples of preprocessing chains that users could build:
> 
> Current implementation:
> 
>     * 2D input -> regrid -> multimodel stats -> area stats
> 
>     * 3D input -> extract levels -> regrid -> multimodel stats -> volume stats
> 
>     * daily input -> multimodel stats (fails because of 360 day + 365 day calendars) -> monthly statistics
> 
> 
> Whereas if we would move multimodel stats to the end, the above examples would simplify to
> 
>     * 2D input -> area stats -> multimodel stats
> 
>     * 3D input -> volume stats -> multimodel stats
> 
>     * daily input -> monthly statistics -> multimodel stats (works because all calendars have 12 months)
> 
> 
> so we would loose the regrid and extract levels functions that introduce inaccuracies.

Sounds interesting, but I think it must be tested well, because it can change results if there is anything non-linear involved. I remember there was some issue long time ago,  when suddenly the global mean temperature was not the same as expected. This could possibly cause similar things.

**Comment by katjaweigel** [comment] 2021-07-08 09:03
Some recipes, where this order play a role already use "custom_order" to set it the way @bouweandela proposes, e.g. esmvaltool/recipes/recipe_ocean_bgc.yml and esmvaltool/recipes/recipe_ocean_example.yml

**Comment by Peter9192** [comment] 2021-07-08 09:06
> Some recipes, where this order play a role already use "custom_order" to set it the way @bouweandela proposes, e.g. esmvaltool/recipes/recipe_ocean_bgc.yml and esmvaltool/recipes/recipe_ocean_example.yml

Yep, same for `recipe_kcs.yml`

**Comment by bouweandela** [comment] 2021-07-08 10:30
I just looked through all recipes in the ESMValTool repository and there is no scientific recipe that would be impacted by this change in order.

**Comment by sloosvel** [comment] 2021-07-08 11:03
If that's what is agreed on, I have some time to implement the changes.

**Comment by zklaus** [comment] 2021-07-08 11:56
That would be great, @sloosvel! For the test, you can have a look at the similar test that @Peter9192 linked above https://github.com/ESMValGroup/ESMValCore/issues/1213#issuecomment-875677347.

To be clear, I think we agree that the multi-model statistics should remove ancillary variables and cell measures, at least when they are conflicting.
Then, perhaps in a second step, we can consider changing the order of the preprocessor steps to minimize the impact of this removal and to reap the benefits of simplified workflows.

**Comment by bouweandela** [comment] 2021-07-09 07:54
I created a new issue for changing the default preprocessor order:  #1221

**Comment by jvegasbsc** [comment] 2021-07-09 08:54
> Maybe changing the default preprocessor order is too big a change for a patch release and we should wait with that for v2.4?

I think we should wait. It is not only that is too big for a patch, it is too big to be merged so soon before any kind of release

**Closed** 2021-07-12 15:07 UTC
